# Lint tests run on PR
# but should not run after push to main because reporting
# these after push is meaningless to the building of the package
name: lint

on:
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: ["ubuntu-22.04"]
        python-version: ["3.8", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install C dependencies
        run: |
          sudo apt-get install -y keyutils libkeyutils-dev

      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          pip install virtualenv tox tox-gh-actions cython

      - name: Test Lint
        run: tox -e lint,radon
